# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
      - duplicate
      - wontfix
    authors:
      - dependabot
  categories:
    - title: 🙌 Notable Changes
      labels:
        - notable
    - title: 💥 Breaking Changes
      labels:
        - breaking
    - title: 🚀  New Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 🏠 Internal
      labels:
        - internal
    - title: Other Changes
      labels:
        - '*'
