name: Publish

on:
   push:
    branches:
      - main

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it      
      - uses: actions/checkout@v2
        with:
      # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: "0"
          
      - name: Configure CI Git User
        run: |
          git config --global user.name '@julczka'
          git config --global user.email 'julczka@users.noreply.github.com'
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_PAT@github.com/umbraco/Umbraco.UI
        env:
          GITHUB_PAT: ${{ secrets.JULCZKA_PAT }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm -v
      - run: npm ci

      - run: npm run build:prod

      - name: Authenticate with Registry
        run: |
          echo "@umbraco-ui:registry=https://registry.npmjs.org/" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.JULCZKA_AUTOMATION_NPM_TOKEN}}

      - name: Publish package
        run: npm run lerna:publish
        env:
          GH_TOKEN: ${{ secrets.JULCZKA_PAT }}
          GITHUB_TOKEN: ${{ secrets.JULCZKA_PAT }}
          NPM_TOKEN: ${{ secrets.JULCZKA_AUTOMATION_NPM_TOKEN}}
  