name: Publish

on:
   push:
    branches:
      - main

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it      
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm -v
      - run: npm ci

      - run: npm run build:prod

      - name: Authenticate npm with the GPR
        uses: jgierer12/npm-auth-gpr@v1.0.1
        with:
          token: ${{ secrets.UMBRACO_PUBLISH_NPM_TOKEN }}

      - name: Publish package
        run: npm run lerna:publish
  